name: Notify Microsoft Teams

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
    types: [opened, reopened, closed, edited, assigned, review_requested, review_request_removed, labeled, unlabeled, synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Microsoft Teams notification
        uses: wei/httppost-action@v1
        with:
          url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          data: '{"text": "New push/pull request: ${{ github.repository }} - ${{ github.event_name }} by ${{ github.actor }}"}'
